### ISSUE TITLE
Error in demo step 6, enabling webcam

### ISSUE THREAD

**Issue by razor23** [projectclarify/clarify#203]
/kind bug

## Bug Report

**Current Behavior**

Step 6 throws an error

name 'widgets' is not defined

**Input Code**
- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-48525fbf1095> in <module>()
----> 1 enable_webcam_button = widgets.Button(description="Enable webcam")
      2 output = widgets.Output()
      3 def wrapper(_):
      4   _ = take_photo()
      5   print("Good to go!")

NameError: name 'widgets' is not defined**

**Comment by cwbeitel** [comment]
Thanks for your question @razor23 if you look at line 18 in step 5 that's where `widgets` is imported:

```python
import ipywidgets as widgets
```

so if step 6 is giving that error it means 6 is being run without having run 5 within this session (either having run it then reset the session or not having run it). Go back and run step 5 which should fix it if you previously ran steps 1-3.

If you haven't run steps 1-3 yet the guaranteed way to fix it is to go to Runtime > factory reset runtime and start over running 1-3, reset the runtime, then continue with 5 and onwards (in order).

Good luck we'll wait to hear how it goes before closing this
